version: 2.1

workfows:
  "develop":
    jobs:
      build:
        docker:
          - image: cirrusci/flutter
        steps:
          - checkout
          - run: flutter docker
          - run: flutter test test
          - run: flutter -v build apk
      test:
        docker:
          - image: circle/flutter
        steps:
          - checkout
          - run:
              name: Unit & Widget Tests
              command: flutter test test
    